--GROUPS
INSERT INTO GROUPS (NAME) VALUES ('Majitel');
INSERT INTO GROUPS (NAME) VALUES ('Admin');
INSERT INTO GROUPS (NAME) VALUES ('Technik');
INSERT INTO GROUPS (NAME) VALUES ('VIP');
INSERT INTO GROUPS (NAME) VALUES ('Hráč');

--USERS
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES ('patrick115', 'ja@patrick115.eu', '$2b$10$xqRyekQ9p1g3jPEepw70C.3ey2.RbtqG9rqJ82iZIP.utWp22uU.i');
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES ('Pepa', NULL, '$2b$10$zCLiylz/914nsCEP8o4PeOzY.3G0jhqsWw4i0IBVduSYj9GlOjU3G');
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES ('XxxHonzikYT_CZ', NULL, '$2b$10$CRsaKZ1VkTNHQ8TIvJHxRuHB3QTJ61pndxDSQz1CPjo9MEM72k6oW');
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES ('Skypad6000', NULL, '$2b$10$E9dAayrcJB9Bhg3GXeqAM.frCH8tX.DQ.IRIKLsw9qTPJkJxaiJ5u');
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES ('Vikikle', NULL, '$2b$10$NxUEkugLTrY6y/lRUkn18OUjH.u7/d8akuswP5Axzqg31/d4TQBue');
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES ('Bagetak', NULL, '$2b$10$bkSgeQR0iWPCrbjIh5hqHuIKWQLyxOwwXmZTIonnTsiPf2fFY58Nq');

--SERVERS
INSERT INTO SERVERS (NAME) VALUES ('Survival');
INSERT INTO SERVERS (NAME) VALUES ('Creative');
INSERT INTO SERVERS (NAME) VALUES ('SkyBlock');

--GROUPS
INSERT INTO USER_HAVE_GROUP (GROUP_ID, USER_ID, SERVER_ID) VALUES (1, 1, 1);
INSERT INTO USER_HAVE_GROUP (GROUP_ID, USER_ID, SERVER_ID) VALUES (1, 1, 2);
INSERT INTO USER_HAVE_GROUP (GROUP_ID, USER_ID, SERVER_ID) VALUES (1, 1, 3);

--Permissions
INSERT INTO PERMISSIONS (NAME, SERVER_ID, USER_ID, REMOVE) VALUES ('*', 1, 2, 0);
INSERT INTO PERMISSIONS (NAME, SERVER_ID, USER_ID, REMOVE) VALUES ('permission.group.addhigher', 2, 2, 0);

COMMIT;