// EXERCISE:
// You can write all the code natively (for cycles and such) or you can use some advanced functions which JS arrays provides in case you see them fit
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
// There can be multiple solutions to each task, solve it as you see fit.
// You will work with array `numbers` which will be generated by code (code below) in every task.
// Write these functions:

// This block generates array with random length with values between 1-100
let numbers = [];
const length = Math.ceil(Math.random() * 10) + 5;
for (let i = 0; i < length; i = i + 1) {
    numbers.push(Math.ceil(Math.random() * 100));
}

// a) Function which will print to console a whole array
const printArray = (numbers) => {
    // Your code:
    console.log(numbers);
};
printArray(numbers);

// b) Function which will print to console the length of array
const printLength = (numbers) => {
    // Your code:
    console.log(numbers.length);
};
printLength(numbers);

// c) Function which will print to console the first element of array
const printFirstItem = (numbers) => {
    // Your code:
    console.log(numbers[0]);
};
printFirstItem(numbers);

// d) Function which will print to console the last element
const printLastItem = (numbers) => {
    // Your code:
    console.log(numbers[numbers.length - 1]);
};
printLastItem(numbers);

// e) Function which will print to console the largest number (You can check Math functions)
const printLargestItem = (numbers) => {
    // Your code:
    console.log(Math.max(...numbers));
};
printLargestItem(numbers);

// f) Function which will print to console the smallest number (You can check Math functions)
const printSmallestItem = (numbers) => {
    // Your code:
    console.log(Math.min(...numbers));
};
printSmallestItem(numbers);

// g) Function which will print to console the sum of all numbers in array (You can check reduce function)
const printSum = (numbers) => {
    // Your code:
    console.log(numbers.reduce((a, b) => a + b, 0));
};
printSum(numbers);

// h) Function which will print to console the difference between the largest and the smallest number (You can check Math functions)
const printSALDifference = (numbers) => {
    // Your code:
    console.log(Math.max(...numbers) - Math.min(...numbers));
};
printSALDifference(numbers);

// i) Function which will print to console the average of all numbers (You can check reduce function)
const printAverage = (numbers) => {
    // Your code:
    console.log(numbers.reduce((a, b) => a + b, 0) / numbers.length);
};
printAverage(numbers);

// j) Function which will print to console the index of largest number (You can check Math functions)
const printLargestsIndex = (numbers) => {
    // Your code:
    const biggest = Math.max(...numbers);
    const index = numbers.findIndex((n) => n === biggest);
    console.log(index);
};
printLargestsIndex(numbers);

// k) Function which will print to console the even numbers (not the array of even numbers),
// if array doesn't contain any even number, show text "Even number isn't in array"
const printEvenNums = (numbers) => {
    // Your code:
    const even = numbers.filter((n) => n % 2 === 0);
    console.log(
        even.length === 0 ? "Even number isn't in array" : even.join(", "),
    );
};
printEvenNums(numbers);

// l) Function which will multiple by 2 every number in array and print the array to console
// Example: printNumsMultipliedBy2([1,2,3]) -> [2,4,6]
const printNumsMultipliedBy2 = (numbers) => {
    // Your code:
    console.log(numbers.map((n) => n * 2));
};
printNumsMultipliedBy2(numbers);
