# Generated by Django 5.0.6 on 2024-05-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('anime', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimeFigures.figure')),
            ],
        ),
        migrations.AddField(
            model_name='figure',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimeFigures.manufacturer'),
        ),
        migrations.CreateModel(
            name='ProfileComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='AnimeFigures.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='AnimeFigures.user')),
            ],
        ),
        migrations.CreateModel(
            name='FigureComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimeFigures.figure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimeFigures.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimeFigures.figure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimeFigures.user')),
            ],
        ),
    ]
