# Generated by Django 5.0.6 on 2024-05-14 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeFigures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
