# Generated by Django 5.0.6 on 2024-05-14 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeFigures', '0002_user_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figure',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AnimeFigures.user'),
        ),
    ]
