[package]
name = "week07-exercises"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.8"
rayon = "1"
humansize = "2"
anyhow = "1.0.100"
