# This is a workspace, which combines several crates together.
# They all share the same target directory, compilation options, Cargo profiles, etc.
[workspace]
members = [
    "assignments",
    "displayme"
]
resolver = "2"
