# files
password_file password
acl_file acl
allow_anonymous false

#mqtt
listener 1883
protocol mqtt

#ws
listener 9999
protocol websockets

#agent things
connection agent-to-server-bridge
address pcfeib425t.vsb.cz:1883

remote_username server
remote_password Broker

topic /mschat/# both 0

#persisence
queue_qos0_messages true
persistence true
persistence_location ./data/
persistent_client_expiration 7d
max_queued_messages 1000
