/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Actor {
  age: number;
  firstname: string;
  id: Generated<number>;
  lastname: string;
}

export interface Cast {
  actor_id: number;
  movie_id: number;
}

export interface Movie {
  id: Generated<number>;
  name: string;
  studio: string;
  year: number;
}

export interface Rating {
  id: Generated<number>;
  movie_id: number;
  rating: number;
  user_id: number;
}

export interface Review {
  id: Generated<number>;
  movie_id: number;
  text: string;
  user_id: number;
}

export interface StarredMovie {
  movie_id: number;
  user_id: number;
}

export interface User {
  email: string;
  id: Generated<number>;
  password: string;
  username: string;
}

export interface DB {
  actor: Actor;
  cast: Cast;
  movie: Movie;
  rating: Rating;
  review: Review;
  starred_movie: StarredMovie;
  user: User;
}
