# Generated by Django 5.0.6 on 2024-05-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeFigures', '0003_figure_added_figure_added_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FigureComments',
            new_name='FigureComment',
        ),
        migrations.RenameModel(
            old_name='ProfileComments',
            new_name='ProfileComment',
        ),
        migrations.RenameModel(
            old_name='UserLikes',
            new_name='UserLike',
        ),
    ]
