# Generated by Django 5.0.6 on 2024-05-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeFigures', '0004_rename_figurecomments_figurecomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurecomment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profilecomment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
